# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            UCB-Squirrels
tagline:          'A CIDIMEC group for Computer Vision research based on OAK-D devices for the OpenCV AI Competition'
description:      'A CIDIMEC group for Computer Vision research based on OAK-D devices for the OpenCV AI Competition'
url:              http://hyde.getpoole.com
baseurl:          /

remote-theme:     poole/hyde

author:
  name:           'UCB-Squirrels'
  url:            https://cidimec.github.io/UCB-squirrels/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cidimec/UCB-squirrels/
